services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: cyber-incident-tracker:1.0
    restart: always
    ports:
      - 8080:80
    environment:
      DB_HOST: db
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      db:
        # per vedere se lo stato è healthy
        condition: service_healthy
    container_name: cybertracker-app

  db:
    build:
      context: .
      dockerfile: Dockerfile
      target: db
    image: cyber-incident-db:1.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # persistenza per mysql
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "cybertracker", "-pcyberpass"]
      interval: 10s
      timeout: 5s
      retries: 5

    container_name: cybertracker-db

volumes:
  mysql_data: